name: flutter_model_gen_example
description: Example app for flutter_model_gen

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  flutter_model_gen:
    path: ../
  json_annotation: ^4.9.0
  injectable: ^2.5.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
  test: ^1.25.15
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4


flutter:
  uses-material-design: true
