name: flutter_gen
description: A sample command-line application to generate a get_it and Injectable project structure.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.8.1
  injectable: ^1.5.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.6
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.7

executables:
  flutter_gen:
    main: bin/flutter_gen.dart

