name: flutter_model_gen
description: |
  `flutter_model_gen` automates model class generation with `json_serializable`, `injectable`, and `get_it`, including DI setup for `clean architecture`

version: 1.1.0

homepage: https://github.com/jayvibespro/flutter_gen
repository: https://github.com/jayvibespro/flutter_gen
license: MIT

environment:
  sdk: ^3.4.3

dependencies:
  json_annotation: ^4.9.0
  injectable: ^2.5.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4

executables:
  flutter_model_gen:

example:
  path: example/

